name: Build and Deploy to GH Pages

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    #- run: npm test
    - run: npm run build
    - run: npm run export
    - run: touch ./out/.nojekyll

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out# Nome della action
name: Deploy React App to GH pages

# "evento" che triggera la action
on:
  push:
    branches: [main]

# setup della action
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # versione di node.js da utilizzare
        node-version: [16]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      ## codice custom
      - run: npm ci
      #- run: npm test
      - run: npm run build

      ## Presa dal marketplace
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build